const article = [
    "When Joe Biden goes to Mass at his home parish in Delaware, the press observes from a designated area on the edge of the property, 50 yards away. Peering through the bars of a black wrought-iron fence, they can see the small parking lot where his motorcade arrives — state troopers first, then the black SUVs. Anyone who strays from the spot is met with surprising speed and firmness by a member of the parish and directed to please return to the perimeter.",
    " Archbishop Joseph F. Naumann of Kansas City said the president needed to “stop defining himself as a devout Catholic” and “acknowledge that his view on abortion is contrary to Catholic moral teaching.” Biden, he said, “should know that after 78 years as a Catholic.” In April, Cardinal Raymond Burke, a leading critic of Pope Francis, called Biden an “apostate.”",
    "If it is at all jarring to hear two strangers speaking authoritatively about a president’s soul, you can find reams of discussion about it on Catholic Reddit, or on the more sympathetic Catholic Twitter, or in incremental coverage by the Catholic media, a lively ecosystem of left-wing and right-wing outlets, where bishops are always popping up in the news to chide Biden, attack Biden or defend Biden. When Biden chose Kamala Harris as his running mate",
    "Then came the most public rebuke of all. This June, in a stunning open debate, the United States Conference of Catholic Bishops, the collection of bishops and cardinals that make up the church’s U.S. hierarchy, weighed moving forward with a document providing justification for denying pro-choice politicians from taking communion, the spiritual heart of Catholicism and the fundamental ritual of the faith. The conference, which will continue the debate at its next meeting in November, has labeled his presidency a “difficult and complex situation.”",
    "If it’s personal, it certainly isn’t private. It is a debate in full public view, a collision of religion and politics never seen in the American presidency — with a clash between his stance on abortion and church dogma now unavoidable. The Supreme Court’s decision this week to allow a highly restrictive Texas abortion law to take effect — and Biden’s public statement that the law “blatantly violates the constitutional right established under Roe v.",
    "Questions about the issue tend to grate on the White House. At a press briefing last week, Owen Jensen, a reporter from EWTN, a conservative Catholic news outlet, was loudly trying to ask a question about Biden’s faith. It wasn’t the first time he’d sparred with press secretary Jen Psaki, who turned toward the interruption with a flash of annoyance. “Why does the president support abortion,” Jensen shouted, “when his own Catholic faith teaches abortion is morally wrong?”",
    "At St. Joseph’s, Biden emerged from the car dressed in light blue shirt sleeves and walked the familiar path through the graveyard that surrounds the church, within view of the place where he buried his wife, his daughter, his father, his mother, and his son. The shouting accompanied him to the front door.",
    "And yet the president’s faith is one of the most public things about him. You can read it on his body: the way he turns his eyes upward, or crosses himself, or fingers the rosary around his left wrist, his late son Beau’s, the one he wore before he died. Biden’s faith is always on display, and therefore so is his grief, his Irishness, his Irish-gothicness, his brashness,",
    "At the heart of the communion dispute, for Biden, is a question of authenticity and identity. “The implication is that he’s being phony,” said Bishop John Stowe of Lexington, Ky., describing the view of the bishops who view Biden as a problem. “That he’s being phony when he travels with a rosary in his pocket or goes out of his way to attend Mass every Sunday. I don’t see any reason not to take him at his word that he’s done that all of his life.” Religious identity was a matter of such publicness that is a measurable reason Biden got to the White House. His campaign built a big and robust faith outreach program, helping him make small gains in the right places:",
    "When the campaign dedicated a prime-time speech to Biden’s faith at the Democratic convention last summer, Sen. Chris Coons got the assignment. Coons grew up in Hockessin, Del., and now holds Biden’s old Senate seat, an office he once served as an intern. Even for a close friend, it was a difficult task. “I will confess I was initially a little hesitant,” Coons told me. He reached out to Biden and his sister Valerie Biden Owens — “just to say, you know, are you sure? And just to say, frankly, this is a very private matter.”",
    "The story she told him went as follows: When Biden was in the Senate, he was a regular guest on the Sunday shows, often while traveling. It was this press secretary’s job to make sure she knew a parish nearby where he could attend Mass before or after his TV hit. She also came from an Irish Catholic family and had worked with Biden for years — she was comfortable with him. One day she turned to him, joking, and said, “You know, senator, it’s not like there’s some nun up in the sky who’s got a chalk blackboard and is keeping score of how many Sundays you actually make it to Mass."
]